using Microsoft.EntityFrameworkCore;
using MovieApp.ENTITY;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MovieApp.DATA.Concrete.EfCore
{
    public static class SeedData
    {
        public static void Seed()
        {
            var context = new MovieContext();
            //tüm mig'ler uygulandığı için veriler eklenebilir.
            if(context.Database.GetPendingMigrations().Count() == 0)
            {
                if(context.Categories.Count() == 0)
                {
                    context.Categories.AddRange(Categories);
                }
                if(context.Movies.Count() == 0)
                {
                    context.Movies.AddRange(Movies);
                }
            }
            context.SaveChanges();
        }
        private static Category[] Categories =
{
                new Category {Name = "Action Films", Url="action"},
                new Category {Name = "Dramatic Films", Url="dramatic"},
                new Category {Name = "History Films", Url="history"},
                new Category {Name = "Thriller Film", Url= "thriller"},
                new Category {Name = "Science-Fiction Films", Url="science-fiction"},
                new Category {Name = "Romantic Films", Url="romantic"}
        };
        private static Movie[] Movies =
{

                new Movie {MovieName="One Flew Over the Cuckoo's Nest",Url="one-flew-over-the-cuckoos-nest", Director="Milos Forman", Genre="Dramatic Film", ReleaseYear=1975, Image="Guguk-kusu.jpg", CategoryId=1, Price=45, IsApproved=true, MovieStory="Randle P. McMurphy is a prisoner who pretends to be crazy to get out of working at the prison where he is incarcerated. When his attitude starts to get in the eyes of the prison authority, he is sent to a mental hospital for diagnosis after a while and it is decided that he will stay there. Randle also attracts attention at the hospital for not following the rules of the institution and his relationships with his friends. Soon, nurse Ratched, a cold-mannered, sullen, domineering attendant, keeps a close eye on Randle and begins to monitor his every move. The tension between two extremely Decadent characters such as Rathced and Randle will increase even more when Randle starts helping them heal with various activities he has planned for his close friends."},
                new Movie {MovieName="The Boy in the Striped Pyjamas",Url="the-boy-in-the-striped-pyjamas", Director="Mark Herman", Genre="Dramatic & Histroy Film", ReleaseYear=2008, Image="Cizgili-pijamali-cocuk.jpg", CategoryId=2, Price=35,IsApproved=true,  MovieStory="2. In the dark days of World War II, the story of two children trying to become friends. 8-year-old Bruno leaves Berlin with his family and starts living in Poland. He also makes friends in this place where they moved for his father's job. His friend is a Jew who stays behind the wires. Bruno's place of residence is adjacent to the Auschwitz concentration and extermination camp, where 1.5 million Jews were killed. Bruno's mother, who is worried that her son will find out the truth about what happened behind the wires, tries to protect her son from this ”friend”. Based on the novel of the same name by John Boyne, which received excellent reviews worldwide, the film recalls the painful memory of history through the eyes of a young child and reflects the horror of innocence and humanity to the screen in an elegant language."},
                new Movie {MovieName="The Silence of the Lambs",Url="the-silence-of-the-lambs", Director="Jonathan Demme", Genre="Thriller & Dramatic Film", ReleaseYear=1991, Image="Kuzularin-sessizligi.jpg",CategoryId=3, Price=55, IsApproved=true,  MovieStory="Clarice Starlin is an FBI agent. Starlin, an FBI agent, is just about to graduate from the academy. Starlin is an agent who is tasked with going after a terrible deviant. Agent Starlin is going after a notorious killer who kills his victims by skinning them. There is a woman who is in the hands of this notorious killer. Starlin's main task is to save the woman who is in the hands of this killer safely. The killer is literally a psychopath. Getting caught is very difficult. Agent Starlin decides to cooperate with Doctor Hannibal to get to this killer. For this, he knows that he must first gain the trust of this doctor. Agent Starlin comes up with a plan to keep things Decently between the doctor and him and tries to get into his eye."},
                new Movie {MovieName="Once Upon a Time in Hollywood",Url="once-upon-a-time-in-hollywood", Director="Quentin Tarantino", Genre="Dramatic Film", ReleaseYear=2019, Image="Once-upon-a-time-in-hollywood.jpg",CategoryId=1, Price=45, IsApproved=true,  MovieStory = "Rick Dalton is a television series actor. However, Rick wants to step into the film industry. Cliff Booth, who is his double, agrees with him about this. However, with the advancing age of the duo, their chances in Hollywood are also decreasing. Sharon Tate, one of Hollywood's new favorites, is Rick's neighbor. Hollywood's glittering and reckless flow will be interrupted when a group of hippies attack their home."},
                new Movie {MovieName="Forrest Gump",Url="forrest-gump", Director="Robert Zemeckis", Genre="Romantic & Dramatic Film", ReleaseYear=1994, Image="Forrest-gump.jpg",CategoryId=5, Price=65, IsApproved=true, MovieStory = "Forrest Gump, who has difficulty even entering public schools due to his low intelligence level, is achieving achievements that baffle reason and logic over time. Although his intelligence level is low, Forrest Gump, who is physically and psychologically extremely robust, takes us to a world we cannot imagine in a chain of events that develops over time.For example, interesting situations develop, such as the fact that he met Jenny and fell in love, accidentally met historical people such as Elvis Presley, Kennedy, Nixon. All this is happening over a period of time from the 50s to the end of the 70s.Not limited to that, Gump joins the Vietnam war by pure coincidence. He witnesses the great events of recent American history, even personally knows about some of them. But unfortunately, he cannot fully realize how important the consequences of what he does unknowingly have."},
                new Movie {MovieName="Fight Club", Url="fight-club",Director="David Fincher", Genre="Dramatic Film", ReleaseYear=1999, Image="Dovus-kulubu-fight-club.jpg",CategoryId=1, Price=45, MovieStory = "The unnamed narrator is a man struggling with his monotonous life and insomnia. The narrator, who does not have a family and close friends, participates in cancer patients' therapy groups on the advice of his doctor and meets Marla during the meeting. Although Marla was not sick like the Narrator, she attended the group's meetings.Narrator's and Marla's efforts are almost to take a stand against the meaninglessness of consumer culture. It is a reaction of people who have a career but are lonely. The Narrator's generation is essentially a dead generation. It is almost an indication of this that when he returned home after a trip, after seeing that his house was burned down, the only person he could call was Tyler, a soap salesman he met during the trip.\r\nAfter a few glasses of beer, Tyler will provoke our hero to punch himself in the parking lot.This fight that started between them will guide the Narrator's whole life. Dec. After a while, the Narrator moves in with Tyler."},
                new Movie {MovieName="The Dark Night",Url="the-dark-night", Director="Christopher Nolan", Genre="Action & Dramatic Film", ReleaseYear=2008, Image="batman-2-kara-sovalye.jpg",CategoryId=0, Price=75, MovieStory = "The Dark Knight tells the story of Batman, who takes on the task of saving the Streets of Gotham again, which returned to chaos with the appearance of the Joker, who poses a great threat to the public. A place that has been cleared of those who committed crimes may come under threat again after a while, and then the struggle of those who will roll up their sleeves again will come to life more sharply. Batman, Lieutenant Gordon and Prosecutor Harvey Dent came together and pulled this off on the Streets of Gotham, but the Joker, who suddenly appears, Deconstructs things badly. It will not be easy to cope with his genius. Gotham is on the verge of the old chaotic days. Batman begins to question the meaning of his own existence as he strips down to rescuing again. He will really want to understand whether he is actually reducing or multiplying the number of criminals."},
                new Movie {MovieName="Django Unchained",Url="django-unchained", Director="Pascal Schröder", Genre="Action & Dramatic Film", ReleaseYear=2022, Image="Zincirsiz.jpg",CategoryId=4, Price=46, MovieStory = "The story, which begins two years before the American Civil War, follows a tormented slave and a German hunter, Dr. It centers on King Schultz's confrontation. It is up to Django to free Schultz, who is accused of the murder of the Brittle brothers. Because Schultz asks Django for a challenging task in exchange for his freedom. Django, who has successfully completed the mission and regained his freedom, still does not leave Schultz's side; with his superior hunting skills, his goal now is to find Broomhilda and save her from the hands of slave traders."},
                new Movie {MovieName="Pulp Fiction", Url="pulp-fiction",Director="Quentin Tarantino", Genre="Dramatic Film", ReleaseYear=1994, Image="Ucuz-roman-pulp-fiction.jpg",CategoryId = 1,Price=92, MovieStory = "Bounty hunter Butch Coolidge decides to stop paying in a deal with the devil. Honey Bunny and Pumpkin are a pair of robbers who are young and in love with each other, who want to add some action to their lives. Paying Decently, meanwhile, two well-known gangsters, Vincent Vega and Jules, as one of their daily jobs, go to shoot a couple of dishonest young men who are delaying payment to their bosses. Vincent is also assigned to babysit the boss's young and beautiful wife, while his partner decides to end his life of crime. A brave boxer, on the other hand, refuses to cheat for money and flees the city. Fate will bring these Decadent types together as a result of a happy coincidence."},
                new Movie {MovieName="Interstellar",Url="interstellar", Director="Christopher Nolan", Genre="Science Fiction  & Dramatic Film", ReleaseYear=2014, Image="Yildizlararasi.jpg",CategoryId=4, Price = 45, IsApproved=true, MovieStory = "At a time when the world is drowning in disasters and water and resources are about to disappear, Cooper, whose technical skills and abilities are quite good, makes his living farming corn fields. Her whole goal is to be able to provide a safe and secure life for her two children in a world that is on the verge of extinction.Grandpa Donald, who lives with them, takes care of the children, while his daughter Murph, who is only 10 years old, has an amazing intelligence and sixth sense ability. Cooper, who misses the scientist career he left behind, is faced with a rather difficult offer to turn down. Cooper embraced this offer as if it were a duty rather than an opportunity. Because Cooper wants the safety and survival of his family first, and then all of humanity. Although it is a very difficult decision for him to accept this mission, the fact that a great mission has to be performed on behalf of humanity will make him feel responsible and obliged, mobilize his team to gather and dive into the boundless depths of space."},
                new Movie {MovieName="Schindler's List",Url="schindlers-list", Director="Steven Spielberg", Genre="History & Dramatic Film", ReleaseYear=1993, Image="Schindler'sList.jpg",CategoryId=2, Price=75, MovieStory = "The film, based on a real life story, is the 2nd of a German businessman named Oskar Schindler. It is about the fact that he started employing Jewish workers in the factory he founded in Poland during World War II and thus saved the lives of 1,100 Jews."},
                new Movie {MovieName="Seven",Url="seven", Director="David Fincher", Genre="Thriller & Dramatic Film", ReleaseYear=1995, Image="seven.jpg",CategoryId=3, Price=102, MovieStory = "Harper Grace (Dreama Walker) is the popular girl of the high school. With the arrival of the school's new student Kaia (Rachel Melvin) in town, Harper's star begins to fade. Kaia is quick to seduce Adam (Jared Keeso), the lover of Harper's close friend. She is also chasing handsome French teacher Jack Powell (Eric Close). The seven deadly sins begin to surround Harper.."},
                new Movie {MovieName="The Lord of the Rings The Return of the King",Url="the-lord-of-the-rings-the-return-of-the-king", Director="Peter Jackson", Genre="Dramatic & Action Film", ReleaseYear=2003, Image="Yuzuklerin-efendisi-kralin-donusu.jpg",CategoryId=1, Price=63, MovieStory = "Directed by Peter Jackson and J.R.R.it is the third and final film in the Lord of the Rings trilogy, based on the. The third and final volume of The Lord of the Rings, The Return of the King, opens with Gandalf and Pippin heading east to the city of Minas Tirith in Gondor, just after King Théoden and the Cavalry of Rohan leave at the end of The Lord of the Rings. In Minas Tirith, Gandalf and Pippin meet Denethor, who clearly dislikes Gandalf. Pippin offers Denethor his sword at the service of Gondor, due to the fact that Denethor's son Boromir sacrificed his life for the hobbits at the beginning of his quest. A gloomy gloom, which Gandalf calls the Darkness, begins to spread from Mordor and soon covers the entire sky over Minas Tirith. Meanwhile, Aragorn realizes that the Cavalry may not reach the city in time to defend it against the upcoming Deconfliction with Mordor. \r\nAragorn leaves the group with Théoden and decides to take the legendary Paths of the Dead to Gondor. While traveling along the Roads accompanied by Legolas and Gimli, a large army of the Sleepless Dead heed Aragorn's orders and follow him south."},
                new Movie {MovieName="Spiderman",Url="spiderman", Director="Sam Raimi", Genre="Action & Science-Fiction Film", ReleaseYear=2002, Image="spiderman.jpg",CategoryId=0, Price = 89, IsApproved=true, MovieStory = "In Spider-Man, the first film of the series; the life of Peter Parker, an ordinary high school student, changes completely one day when he is bitten by a spider. Because this spider is not an ordinary spider, it is a genetically specially developed subject used for scientific purposes. Peter is no longer the old Peter parker."},
                new Movie {MovieName="Inglourious Basterds",Url="inglourious-basterds", Director="Quentin Tarantino", Genre="Action & Dramatic Film", ReleaseYear=2009, Image="Soysuzlar-cetesi.jpg",CategoryId=1, Price = 65, MovieStory = "Topic 2. the film, which is based on the world war II,tells about the struggle against Nazi Germany.Raine(Brad Pitt) gathers Jewish soldiers around him and organizes them with the aim of retaliating against the enemy.This group, known for inciting bastards,targets Nazi leaders.Those who do not watch should not miss this movie."},
                new Movie {MovieName="The Devil's Advocate",Url="the-devils-advocate", Director="Taylor Hackford", Genre=" Thriller & Dramatic Film", ReleaseYear=1997, Image="devil'sadvocate.jpg",CategoryId=3, Price=45, MovieStory = "The film follows the life of Kevin Lomax (Keanu Reeves), a successful lawyer, who becomes strange after meeting rich businessman John Milton (Al Pacino). Lawyer Kevin Lomax takes success in his business so seriously that even if he knows his clients are guilty, he manages to save them from the hands of justice. After meeting a rich businessman named John Milton, she settles in New York. The psychological problems experienced by his wife after settling in New York will allow lawyer Lomax to get to some facts."},
                new Movie {MovieName="Shutter Island",Url="shutter-island", Director="Martin Scorsese", Genre="Thriller Film", ReleaseYear=2010, Image="zindan-adasi.jpg",CategoryId=3, Price=75, IsApproved=true, MovieStory = "Dungeon Island, like many of Martin Scorsese's films, has the status of a masterpiece again. In the film, two police officers named Teddy Daniels and Chuck Aule go to Ashecliffe Hospital, located in an area called Shutter Island where dangerous mental patients are being treated, to investigate the disappearance of a mental patient named Rachel Solando, and the mysterious events that developed later. The picture of the rebellion they face here and the Decadent work will make this case more and more difficult, and over time the boundaries between the dream and reality will be pushed"},
                new Movie {MovieName="The Last Letter from Your Lover",Url="the-last-letter-from-your-lover", Director="Augustine Frizzell", Genre="Romantic & Dramatic Film", ReleaseYear=2021, Image="The-last-letter-from-your-lover.jpg",CategoryId=5, Price=25, MovieStory = "When Ellie Haworth discovers a top-secret love story dating back to 1965, she decides to reveal all the secrets of the forbidden relationship that is at the center of this relationship. Ellie Haworth is therefore forced to come and go at two different times in this story, which extends both to her own time and to the past. According to the data Ellie Haworth found, she comes across the names of Jennifer Stirling, the wife of a very rich industrialist, and financial journalist Anthony O'Hare at the center of this love story. As soon as Ellie Haworth confirms these names, she becomes unstoppable and begins to unravel the story with the help of an archivist. As Ellie Haworth explores the story, her feelings of love and affection also gradually begin to awaken, and she begins to feel an affinity for this archivist, whom she finds increasingly cute. I wonder if Ellie Haworth has found a true love with this archivist? Will he be able to find out the end of the love full of secrets he is investigating?"}
    };
    }
}
